version: '3'

services:
  prod:
    image: redisphere/prod
    container_name: redisphere-container-test
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb+srv://restankowitz:1234@cluster0.mvwl90e.mongodb.net/?retryWrites=true&w=majority
      - NODE_ENV=production
    command: npm run test

volumes:
  node_modules:
